version: "3.3"
services:
  nginx:
    container_name: ${NGINX_NAME}
    depends_on:
      - client
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
      args:
        DOCKER_NGINX_VERSION: ${DOCKER_NGINX_VERSION}
  client:
    container_name: ${CLIENT_NAME}
    build:
      args:
        DOCKER_NODE_VERSION: ${DOCKER_NODE_VERSION}
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure

  backend:
    container_name: ${BACKEND_NAME}
    build:
      args:
        DOCKER_NODE_VERSION: ${DOCKER_NODE_VERSION}
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./env/backend.env
    restart: on-failure

  mongo:
    image: mongo
    container_name: ${DB_NAME}
    user: ${USER}:${USER}
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    env_file:
      - ./env/mongo.env
    restart: on-failure

networks:
  default:
    external:
      name: ${PROXY_NAME}
