version: "3.3"
services:
  nginx:
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/:/app/
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/:/app/
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
